### ISSUE TITLE
Commnent fg override does not work at NvChad v3.0 

### ISSUE THREAD

**Issue by dro-sh** [NvChad/nvcommunity#24]
I try to use NvChad v3.0. I want to override default comment fg. I use next at `./lua/custom/chadrc.lua`:
```lua
M.ui = {
  hl_override = {
    Comment = { fg = "white" }
  }
}
```

At `:hi` I have next:

```
Comment xxx guifg=#dee1e6 guibg=#1e1e1e
```

Also I try next:
```lua
vim.api.nvim_set_hl(0, "Comment", { fg = "white", bg = "#fe1b50" })

vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
```

It also does not help.

How to fix it?

**Comment by siduck** [comment]
hl_override = {
    Comment = { fg = "white" },
    ["@comment"] = { fg = "white" },
  },
