### ISSUE TITLE
Creating plugin directory

### ISSUE THREAD

**Issue by ambaradan** [NvChad/nvcommunity#7]
Hi @siduck , this is not a request for a issue as much as for information. I was studying the new features introduced by "nvcommunity" and I ported the plugin "Neogit" that I use regularly from `plugins.lua` to the repo (a fork) and I was wondering if it would be appropriate to also add a README in the plugin folder with a short description and the code needed for inclusion in the configuration, this in my opinion would help a lot the users less introduced in the editor to choose their plugins and would facilitate the inclusion.
Also, always better to PR from a separate branch, right?
**A big thank you for all the work you are doing**.

**Comment by siduck** [comment]
@ambaradan hi there, Do  you want to use different Neogit forked repo?

**Comment by ambaradan** [comment]
No, at least if I understand correctly, I fork the repo on my GitHub and create a new branch (nvcommunity_neogit) where I make the changes, usually when I do PR I do it from the separate branch, that's it.
I don't have much experience with GitHub, but in this way the main branch remains clean until, after the necessary checks, the two branches are merged.
Regarding the README file what do you think?

**Comment by siduck** [comment]
@ambaradan you dont have to create a new branch btw

**Comment by ambaradan** [comment]
Okay understood, thanks for the information.
